#!/usr/bin/env python3
"""build-colophon.py — regenerate colophon.js from git history + the GitHub Pages API.

Every number in the site colophon is derived, never typed:
  site est / commits ......... git log
  deployments / last deploy .. GitHub deployments API (gh CLI; falls back to the
                               values cached in the current colophon.js if offline)
  version .................... v{GENERATION}.{case studies in tree}.{commit count}
  updated .................... date this script ran (regenerate before each push)
  lines / pages .............. counted from the working tree (generated files excluded)

Run before a release, alongside build-search-index.py:  python3 build-colophon.py
"""
import json, re, subprocess, sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent
GENERATION = 1  # bump on a ground-up redesign, not a refactor
REPO = "rbabiarz/Product-Designer-Portfolio"

def sh(*args):
    return subprocess.run(args, cwd=ROOT, capture_output=True, text=True).stdout.strip()

def fmt(iso):  # 2026-07-12 -> Jul 12, 2026
    y, m, d = (int(x) for x in iso[:10].split("-"))
    return date(y, m, d).strftime("%b %-d, %Y")

# ── git facts ──────────────────────────────────────────────────────────────
first_commit = sh("git", "log", "--reverse", "--format=%ad", "--date=short").splitlines()[0]
commits = int(sh("git", "rev-list", "--count", "HEAD"))
last_push = sh("git", "log", "origin/main", "-1", "--format=%ad", "--date=short") or first_commit

# ── GitHub Pages deployments (graceful offline fallback) ───────────────────
deploys, last_deploy = None, None
try:
    out = sh("gh", "api", f"repos/{REPO}/deployments?per_page=100", "--paginate", "--jq", ".[].created_at")
    stamps = [s for s in out.splitlines() if s]
    if stamps:
        deploys, last_deploy = len(stamps), max(stamps)[:10]
except Exception:
    pass
if deploys is None:  # offline: reuse the last generated values rather than guessing
    prev = (ROOT / "colophon.js")
    m = prev.exists() and re.search(r'"deploys":\s*(\d+).*?"lastDeploy":\s*"([^"]+)"', prev.read_text())
    if m:
        deploys, last_deploy = int(m.group(1)), m.group(2)
        print("warn: GitHub API unreachable — reusing cached deployment stats", file=sys.stderr)
    else:
        sys.exit("error: GitHub API unreachable and no cached colophon.js to fall back to")

# ── working-tree counts ─────────────────────────────────────────────────────
EXCLUDE_DIRS = {"vendor", "node_modules", "pdf-export", "linkedin-feature", ".git"}
GENERATED = {"search-index.js", "deep-dive.html", "colophon.js"}
loc = 0
for p in ROOT.rglob("*"):
    if p.suffix not in {".html", ".js", ".css", ".py"} or p.name in GENERATED:
        continue
    if any(part in EXCLUDE_DIRS for part in p.parts):
        continue
    loc += sum(1 for _ in p.open(encoding="utf-8", errors="ignore"))
case_studies = len(list(ROOT.glob("*-showcase.html")))
INTERNAL = {"_tilegen.html", "_brandgen.html", "index.html", "arctic-shield.html", "ctoc-dashboard.html"}
pages = len([p for p in ROOT.glob("*.html") if p.name not in INTERNAL])

DATA = {
    "est": fmt(first_commit),
    "deploys": deploys,
    "lastDeploy": last_deploy,
    "lastDeployFmt": fmt(last_deploy),
    "version": f"v{GENERATION}.{case_studies}.{commits}",
    "updated": fmt(date.today().isoformat()),
    "pages": pages,
    "loc": f"{round(loc / 1000)},000",
    "caseStudies": case_studies,
}

JS = """/* colophon.js — the site's build record, injected above the end of every page.
   GENERATED by build-colophon.py — do not edit by hand; regenerate per release.
   Every stat derives from git history and the GitHub Pages deployment API.
   Token-driven with graceful fallbacks so it renders correctly on both the
   homepage token system (--bg/--fg2/--ac2) and the case-study system (--c-*). */
(function () {
  'use strict';
  /* Never render inside an embed: arctic-shield and ctoc-dashboard also run
     as iframes inside the homepage and CTOC case study — the host page
     already carries the colophon. */
  try { if (window.top !== window.self) return; } catch (e) { return; }
  var DATA = __DATA__;
  /* Mount inside the page's token scope. Case-study pages scope their tokens to
     .cs (light/dark via .cs.dark), so a body-level mount would miss them; pages
     with :root tokens (homepages, work, about, deep-dive) mount to body. DC
     pages render .cs with React after load, hence the short retry loop. */
  function findHost() {
    var s = getComputedStyle(document.body);
    if ((s.getPropertyValue('--c-bg') || s.getPropertyValue('--bg')).trim()) return document.body;
    var els = document.querySelectorAll('.cs');
    for (var i = els.length - 1; i >= 0; i--) { if (!els[i].closest('x-dc')) return els[i]; }
    return null;
  }
  /* Pages outside both token systems (games, embedded dashboards, older shells)
     get concrete colors picked by the page's real painted luminance. */
  function paintedBg(el) {
    if (!el) return null;
    var c = getComputedStyle(el).backgroundColor;
    return (c && c !== 'transparent' && !/rgba\(\d+, \d+, \d+, 0\)/.test(c)) ? c : null;
  }
  function pageIsDark() {
    var c = paintedBg(document.body) || paintedBg(document.documentElement);
    if (!c) {
      var best = null, area = 0, kids = document.body.children;
      for (var i = 0; i < kids.length; i++) {
        var r = kids[i].getBoundingClientRect(), a = r.width * r.height;
        if (a > area) { area = a; best = kids[i]; }
      }
      c = paintedBg(best);
    }
    if (!c) return true; // the site's default chrome is dark
    var m = c.match(/\d+(\.\d+)?/g) || [128, 128, 128];
    return (0.2126 * m[0] + 0.7152 * m[1] + 0.0722 * m[2]) / 255 < 0.5;
  }
  function mount(host) {
    if (document.querySelector('.rb-colophon')) return;
    var css = document.createElement('style');
    css.textContent =
      '.rb-colophon{background:var(--c-bg,var(--bg,transparent));border-top:1px solid var(--c-b1,var(--line,rgba(127,127,127,.28)));font-family:Inter,system-ui,sans-serif}' +
      '.rb-colo-in{max-width:1180px;margin:0 auto;padding:44px 40px 140px}' +
      '.rb-colophon .mono,.rb-colo-eyebrow,.rb-colo-stats dt,.rb-colo-row .k,.rb-colo-note{font-family:"JetBrains Mono",ui-monospace,SFMono-Regular,monospace}' +
      '.rb-colo-eyebrow{font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:var(--c-accent,var(--ac2,#7fd6c2));margin-bottom:22px}' +
      '.rb-colo-stats{display:flex;flex-wrap:wrap;gap:14px 44px;margin:0 0 30px;padding:0}' +
      '.rb-colo-stats>div{min-width:120px}' +
      '.rb-colo-stats dt{font-size:9.5px;letter-spacing:.13em;text-transform:uppercase;color:var(--c-muted,var(--fg2,#8a93a6));margin-bottom:5px}' +
      '.rb-colo-stats dd{margin:0;font-family:"JetBrains Mono",ui-monospace,monospace;font-size:15px;font-weight:600;color:var(--c-ink2,var(--fg,inherit))}' +
      '.rb-colo-rows{display:grid;gap:14px;margin-bottom:26px}' +
      '.rb-colo-row{display:grid;grid-template-columns:118px 1fr;gap:16px;align-items:baseline}' +
      '.rb-colo-row .k{font-size:9.5px;letter-spacing:.13em;text-transform:uppercase;color:var(--c-muted,var(--fg2,#8a93a6))}' +
      '.rb-colo-row .v{font-size:13.5px;line-height:1.65;color:var(--c-body,var(--fg2,#a5adbd));max-width:920px}' +
      '.rb-colo-note{font-size:9.5px;letter-spacing:.11em;text-transform:uppercase;line-height:1.9;color:var(--c-muted,var(--fg2,#8a93a6));opacity:.75}' +
      '@media(max-width:720px){.rb-colo-in{padding:34px 20px 150px}.rb-colo-stats{gap:14px 26px}.rb-colo-row{grid-template-columns:1fr;gap:4px}}' +
      /* concrete fallback themes for pages outside both token systems */
      '.rb-colophon.rb-colo-dark{background:#0b1016;border-top-color:rgba(255,255,255,.1)}' +
      '.rb-colo-dark .rb-colo-eyebrow{color:#7fd6c2}' +
      '.rb-colo-dark .rb-colo-stats dd{color:#e7e9ef}' +
      '.rb-colo-dark .rb-colo-stats dt,.rb-colo-dark .rb-colo-row .k,.rb-colo-dark .rb-colo-note{color:#8f97a8}' +
      '.rb-colo-dark .rb-colo-row .v{color:#b6bdc9}' +
      '.rb-colophon.rb-colo-light{background:#fffcf5;border-top-color:rgba(10,8,4,.1)}' +
      '.rb-colo-light .rb-colo-eyebrow{color:#0d5350}' +
      '.rb-colo-light .rb-colo-stats dd{color:#1c2730}' +
      '.rb-colo-light .rb-colo-stats dt,.rb-colo-light .rb-colo-row .k,.rb-colo-light .rb-colo-note{color:#6e6a60}' +
      '.rb-colo-light .rb-colo-row .v{color:#534f48}';
    document.head.appendChild(css);
    var el = document.createElement('section');
    el.className = 'rb-colophon';
    el.setAttribute('aria-label', 'Colophon — how this site is built and shipped');
    el.innerHTML =
      '<div class="rb-colo-in">' +
        '<div class="rb-colo-eyebrow">Colophon &middot; Build Record</div>' +
        '<dl class="rb-colo-stats">' +
          '<div><dt>Site est</dt><dd>' + DATA.est + '</dd></div>' +
          '<div><dt>Deployments</dt><dd>' + DATA.deploys + '</dd></div>' +
          '<div><dt>Last deploy</dt><dd>' + DATA.lastDeployFmt + '</dd></div>' +
          '<div><dt>Version</dt><dd>' + DATA.version + '</dd></div>' +
          '<div><dt>Updated</dt><dd>' + DATA.updated + '</dd></div>' +
        '</dl>' +
        '<div class="rb-colo-rows">' +
          '<div class="rb-colo-row"><span class="k">Built with</span><span class="v">Anthropic Claude Code &middot; Playwright &middot; Figma + MUI kit &middot; VS Code &middot; Python 3 &middot; React 18 (CDN, no build step) &middot; Git &rarr; GitHub Pages</span></div>' +
          '<div class="rb-colo-row"><span class="k">Architecture</span><span class="v">' + DATA.pages + ' self-contained pages, ~' + DATA.loc + ' hand-authored lines, zero npm dependencies, no bundler &mdash; every page is a single file that opens anywhere and deploys as pure static hosting. The interactive layer is bespoke vanilla JS: a photometric engine scored against real parking uniformity targets, an AI AutoLayout demo with ranked candidates, playable decision drills, and client-side search over a Python-generated index. WCAG 2.2 AA target with a standing audit; three-tier design tokens (primitive &rarr; semantic &rarr; component).</span></div>' +
          '<div class="rb-colo-row"><span class="k">AI-paired</span><span class="v">Human-led, AI-accelerated: designed and engineered in pair with Anthropic Claude Code, with Playwright browser automation verifying every change &mdash; the same receipts-over-vibes workflow the case studies argue for. ' + DATA.caseStudies + ' case studies, several of them about designing AI systems people can trust.</span></div>' +
        '</div>' +
        '<div class="rb-colo-note">Stats derived from git history &amp; the GitHub Pages deployment API, regenerated per release &middot; version = generation &middot; case studies &middot; commits</div>' +
      '</div>';
    if (!host) el.classList.add(pageIsDark() ? 'rb-colo-dark' : 'rb-colo-light');
    if (host && host !== document.body) { host.appendChild(el); return; }
    /* Scene-driven shells (the interactive homepage) lock html/body to the
       viewport and scroll layered content inside — a body-end mount would sit
       buried at y≈100vh. When body's flow height is far short of the real
       scroll height, mount after the page's in-flow footer instead. */
    var se = document.scrollingElement || document.documentElement;
    if (document.body.clientHeight + 200 < se.scrollHeight) {
      var foots = document.querySelectorAll('footer');
      for (var i = foots.length - 1; i >= 0; i--) {
        var s = getComputedStyle(foots[i]);
        if (s.position !== 'fixed' && s.display !== 'none' && foots[i].parentElement) {
          foots[i].insertAdjacentElement('afterend', el);
          return;
        }
      }
    }
    /* App shells (the CTOC dashboard) hide document scroll entirely and pan a
       single internal region — mount at the end of that region's content. The
       region may be JS-populated after load, so retry once before settling. */
    if (se.scrollHeight <= se.clientHeight + 50) {
      var best = null, bestH = 0, all = document.querySelectorAll('*');
      for (var j = 0; j < all.length; j++) {
        var st = getComputedStyle(all[j]);
        if (!/(auto|scroll)/.test(st.overflowY)) continue;
        if (all[j].scrollHeight > all[j].clientHeight + 40 && all[j].clientHeight > bestH) {
          best = all[j]; bestH = all[j].clientHeight;
        }
      }
      if (best) { best.appendChild(el); return; }
      if (!mount._retried) {
        mount._retried = 1;
        setTimeout(function () { mount(host); }, 1500);
        return;
      }
    }
    document.body.appendChild(el);
  }
  function boot() {
    /* React (support.js) pages render their token scope after load — retry
       briefly; plain pages mount immediately. */
    var max = document.querySelector('script[src*="support.js"]') ? 12 : 0;
    var tries = 0;
    (function attempt() {
      var h = findHost();
      if (h || tries >= max) mount(h);
      else { tries++; setTimeout(attempt, 250); }
    })();
  }
  /* If a framework re-render swallows the mounted node (homepage heal
     guardian, DC hydration), quietly re-mount — checks a few times, then stops. */
  var ensures = 0;
  function ensure() {
    if (!document.querySelector('.rb-colophon')) boot();
    if (++ensures < 3) setTimeout(ensure, 4000);
  }
  setTimeout(ensure, 4000);
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();
})();
"""

(ROOT / "colophon.js").write_text(JS.replace("__DATA__", json.dumps(DATA)), encoding="utf-8")
print(f"wrote colophon.js — {DATA['version']} · {deploys} deploys · est {DATA['est']} · ~{DATA['loc']} lines · {pages} pages")
