/* colophon.js — the site's build record, injected above the end of every page.
   GENERATED by build-colophon.py — do not edit by hand; regenerate per release.
   Every stat derives from git history and the GitHub Pages deployment API.
   Colors are fixed (the dossier homepage's dark-navy strip is the reference)
   so the build record reads identically everywhere, independent of whether
   the host page is light-themed, dark-themed, or has no token system at all —
   only the mount LOCATION varies per page, never the look. */
(function () {
  'use strict';
  /* Never render inside an embed: arctic-shield and ctoc-dashboard also run
     as iframes inside the homepage and CTOC case study — the host page
     already carries the colophon. */
  try { if (window.top !== window.self) return; } catch (e) { return; }
  var DATA = {"est": "Jun 22, 2026", "deploys": 105, "lastDeploy": "2026-07-18", "lastDeployFmt": "Jul 18, 2026", "version": "v1.10.110", "updated": "Jul 18, 2026", "pages": 27, "loc": "75,000", "caseStudies": 10};
  /* Mount inside the page's token scope purely for DOM placement (so it lands
     in natural document flow, not free-floating outside a themed wrapper).
     Case-study pages scope layout to .cs; pages with :root tokens (homepages,
     work, about, deep-dive) mount to body. DC pages render .cs with React
     after load, hence the short retry loop. Colophon colors never follow
     either scope — see the fixed palette below. */
  function findHost() {
    var s = getComputedStyle(document.body);
    if ((s.getPropertyValue('--c-bg') || s.getPropertyValue('--bg')).trim()) return document.body;
    var els = document.querySelectorAll('.cs');
    for (var i = els.length - 1; i >= 0; i--) { if (!els[i].closest('x-dc')) return els[i]; }
    return null;
  }
  function mount(host) {
    if (document.querySelector('.rb-colophon')) return;
    var css = document.createElement('style');
    css.textContent =
      /* fixed dark-navy palette — the dossier homepage's build record, verbatim,
         on every page regardless of that page's own light/dark theme */
      '.rb-colophon{background:#0b1016;border-top:1px solid rgba(255,255,255,.1);font-family:Inter,system-ui,sans-serif}' +
      '.rb-colo-in{max-width:1180px;margin:0 auto;padding:44px 40px 140px}' +
      '.rb-colophon .mono,.rb-colo-eyebrow,.rb-colo-stats dt,.rb-colo-row .k,.rb-colo-note{font-family:"JetBrains Mono",ui-monospace,SFMono-Regular,monospace}' +
      '.rb-colo-head{display:flex;align-items:baseline;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:22px}' +
      '.rb-colo-eyebrow{font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:#7fd6c2;margin:0}' +
      '.rb-colo-src{font-family:"JetBrains Mono",ui-monospace,monospace;font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:#8f97a8;text-decoration:none;white-space:nowrap;transition:color .15s ease}' +
      '.rb-colo-src:hover{color:#7fd6c2}' +
      '.rb-colo-src:focus-visible{outline:2px solid #7fd6c2;outline-offset:3px;border-radius:2px}' +
      '.rb-colo-stats{display:flex;flex-wrap:wrap;gap:14px 44px;margin:0 0 30px;padding:0}' +
      '.rb-colo-stats>div{min-width:120px}' +
      '.rb-colo-stats dt{font-size:9.5px;letter-spacing:.13em;text-transform:uppercase;color:#8f97a8;margin-bottom:5px}' +
      '.rb-colo-stats dd{margin:0;font-family:"JetBrains Mono",ui-monospace,monospace;font-size:15px;font-weight:600;color:#e7e9ef}' +
      '.rb-colo-rows{display:grid;gap:14px;margin-bottom:26px}' +
      '.rb-colo-row{display:grid;grid-template-columns:118px 1fr;gap:16px;align-items:baseline}' +
      '.rb-colo-row .k{font-size:9.5px;letter-spacing:.13em;text-transform:uppercase;color:#8f97a8}' +
      '.rb-colo-row .v{font-size:13.5px;line-height:1.65;color:#b6bdc9;max-width:920px}' +
      '.rb-colo-note{font-size:9.5px;letter-spacing:.11em;text-transform:uppercase;line-height:1.9;color:#8f97a8;opacity:.75}' +
      '.rb-colo-rights{margin-top:12px;font-family:Inter,system-ui,sans-serif;font-size:11.5px;line-height:1.7;color:#8f97a8;opacity:.75}' +
      '@media(max-width:720px){.rb-colo-in{padding:34px 20px 150px}.rb-colo-stats{gap:14px 26px}.rb-colo-row{grid-template-columns:1fr;gap:4px}}';
    document.head.appendChild(css);
    var el = document.createElement('section');
    el.className = 'rb-colophon';
    el.setAttribute('aria-label', 'Colophon — how this site is built and shipped');
    el.innerHTML =
      '<div class="rb-colo-in">' +
        '<div class="rb-colo-head">' +
          '<div class="rb-colo-eyebrow">Colophon &middot; Build Record</div>' +
          '<a class="rb-colo-src" href="https://github.com/rbabiarz/Product-Designer-Portfolio" target="_blank" rel="noopener">View source on GitHub &#8599;</a>' +
        '</div>' +
        '<dl class="rb-colo-stats">' +
          '<div><dt>Site est</dt><dd>' + DATA.est + '</dd></div>' +
          '<div><dt>Deployments</dt><dd>' + DATA.deploys + '</dd></div>' +
          '<div><dt>Last deploy</dt><dd>' + DATA.lastDeployFmt + '</dd></div>' +
          '<div><dt>Version</dt><dd>' + DATA.version + '</dd></div>' +
          '<div><dt>Updated</dt><dd>' + DATA.updated + '</dd></div>' +
        '</dl>' +
        '<div class="rb-colo-rows">' +
          '<div class="rb-colo-row"><span class="k">Built with</span><span class="v">Anthropic Claude Code &middot; Playwright &middot; Figma + MUI kit &middot; Cursor &middot; Python 3 &middot; React 18 (CDN, no build step) &middot; Git &rarr; GitHub Pages</span></div>' +
          '<div class="rb-colo-row"><span class="k">Architecture</span><span class="v">' + DATA.pages + ' self-contained pages, ~' + DATA.loc + ' hand-authored lines, zero npm dependencies, no bundler &mdash; every page is a single file that opens anywhere and deploys as pure static hosting. The interactive layer is bespoke vanilla JS: a photometric engine scored against real parking uniformity targets, an AI AutoLayout demo with ranked candidates, playable decision drills, and client-side search over a Python-generated index. WCAG 2.2 AA target with a standing audit; three-tier design tokens (primitive &rarr; semantic &rarr; component).</span></div>' +
          '<div class="rb-colo-row"><span class="k">AI-paired</span><span class="v">Human-led, AI-accelerated: designed and engineered in pair with Anthropic Claude Code, with Playwright browser automation verifying every change &mdash; the same receipts-over-vibes workflow the case studies argue for. ' + DATA.caseStudies + ' case studies, several of them about designing AI systems people can trust.</span></div>' +
        '</div>' +
        '<div class="rb-colo-note">Stats derived from git history &amp; the GitHub Pages deployment API, regenerated per release &middot; version = generation &middot; case studies &middot; commits</div>' +
        '<div class="rb-colo-rights">All images in case studies from CLS are &copy; 2026 Signify &ndash; Cooper Lighting Canada Limited. All rights reserved.</div>' +
      '</div>';
    if (host && host !== document.body) { host.appendChild(el); return; }
    /* Scene-driven shells (the interactive homepage) lock html/body to the
       viewport and scroll layered content inside — a body-end mount would sit
       buried at y≈100vh. When body's flow height is far short of the real
       scroll height, mount after the page's in-flow footer instead. */
    var se = document.scrollingElement || document.documentElement;
    if (document.body.clientHeight + 200 < se.scrollHeight) {
      var foots = document.querySelectorAll('footer');
      for (var i = foots.length - 1; i >= 0; i--) {
        var s = getComputedStyle(foots[i]);
        if (s.position !== 'fixed' && s.display !== 'none' && foots[i].parentElement) {
          foots[i].insertAdjacentElement('afterend', el);
          return;
        }
      }
    }
    /* App shells (the CTOC dashboard) hide document scroll entirely and pan a
       single internal region — mount at the end of that region's content. The
       region may be JS-populated after load, so retry once before settling. */
    if (se.scrollHeight <= se.clientHeight + 50) {
      var best = null, bestH = 0, all = document.querySelectorAll('*');
      for (var j = 0; j < all.length; j++) {
        var st = getComputedStyle(all[j]);
        if (!/(auto|scroll)/.test(st.overflowY)) continue;
        if (all[j].scrollHeight > all[j].clientHeight + 40 && all[j].clientHeight > bestH) {
          best = all[j]; bestH = all[j].clientHeight;
        }
      }
      if (best) { best.appendChild(el); return; }
      if (!mount._retried) {
        mount._retried = 1;
        setTimeout(function () { mount(host); }, 1500);
        return;
      }
    }
    document.body.appendChild(el);
  }
  function boot() {
    /* React (support.js) pages render their token scope after load — retry
       briefly; plain pages mount immediately. */
    var max = document.querySelector('script[src*="support.js"]') ? 12 : 0;
    var tries = 0;
    (function attempt() {
      var h = findHost();
      if (h || tries >= max) mount(h);
      else { tries++; setTimeout(attempt, 250); }
    })();
  }
  /* If a framework re-render swallows the mounted node (homepage heal
     guardian, DC hydration), quietly re-mount — checks a few times, then stops. */
  var ensures = 0;
  function ensure() {
    if (!document.querySelector('.rb-colophon')) boot();
    if (++ensures < 3) setTimeout(ensure, 4000);
  }
  setTimeout(ensure, 4000);
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();
})();
